config/routes.rb
Rails.application.routes.draw do


  get 'blogs/index'
  get 'blogs/new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get "/signin" => "sessions#new"
post "/signin" => "users#signin"
post "/logout" =>  "sessions#destroy"

root "users#index"

  resources :users
  resources :blogs 
  resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :blogs
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user = User.find_by_id(session[:user_id])
  end

  helper_method :current_user, :logged_in?

  def logged_in?
    current_user != nil
  end
  

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
    @user = current_user
  end

  def new
    @blog = Blog.new
    @user = current_user
  end

  def create
    blog = Blog.new(blog_params)
    blog.user_id = current_user.id
    if blog.save
      redirect_to "/blogs"
    else
      render "/blogs/new"
  end
end

def show
  @blog = Blog.find(params[:id])
  @user = current_user
  @comment = Comment.new
end

def edit
  @blog = Blog.find(params[:id])
  @user = current_user
end

def update
  @blog = Blog.find(params[:id])
  if @blog.update(blog_params)
    redirect_to "/blogs"
  else
    render edit_blog_path
  end
end

def destroy
  blog = Blog.find(params[:id])
  blog.destroy
  redirect_to "/blogs"
end

private

def blog_params
  params.require(:blog).permit(:title, :content, :user_id)
end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @blog = Blog.find(params[:blog_id])
    c = Comment.new(comment_params)
    c.user_id = current_user.id
    c.blog_id = @blog.id
    if c.save
      redirect_to "/blogs"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @user = current_user
  end

  def update
    @comment = Comment.find(params[:id])
    @blog = @comment.blog
    if @comment.update(comment_params)
      redirect_to "/blogs"
    else
      render edit_blog_path
    end
  end

  def destroy
    # @blog = Blog.find(params[:blog_id])
    # @comment = @blog.comments.destroy(params[:id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to "/blogs"
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id, :blog_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = current_user
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user

  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      redirect_to "/"
    else
      render "/users/new"
    end
  end

def signin
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to "/users/#{session[:user_id]}"
      flash[:notice] = "succesfully signed in"
    else
      redirect_to :controller => "sessions", :action => "new"
      flash[:notice] = "try again"
    end
end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to "/users"
    else
      render edit_user_path
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
      redirect_to "/"
  end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :password, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<h1 class="editBlogTitle">Edit Blog: </h1>

<div class="blogEditPage">
<%= form_for @blog do |f| %>
Title: <%= f.text_field :title %>
Content: <%= f.text_field :content %>
<%= f.submit "Edit Blog"%>
</div>
<% end %>
<br>
<div class="deleteBlogBtn"><%= link_to "Delete Blog", blog_path, method: :delete %></div>

</div>

app/views/blogs/index.html.erb
<h1 class="multipleBlogs">List of Blogs</h1>

<div class="blogPostList">
  <% @blogs.each do |b| %>
    <div class="blogTitle"><%= b.title %></div>
    <br>
    <div class="blogContent"><%= b.content %></div>
    <div class="blogUser"><%= b.user.username %></div>

      <a href="/blogs/<%= b.id %>">Make a comment</a>

      <br>
      <br>
      <% b.comments.each do |c| %>
      <% if c.user_id === current_user.id %>
      <a href="/comments/<%= c.id %>/edit">Edit comment</a>
      <% end %>
      <div class="commentSection"><%= c.content %></div>
      <br>

      <% end %>

      <hr>
      <% end %>
</div>

app/views/blogs/new.html.erb
<h1 class="createBlogTitle">Create a new Blog: </h1>

<div class="createBlog">
<%= form_for @blog do |f| %>
Title: <%= f.text_field :title %>
Content: <%= f.text_field :content %>
<%= f.submit "Create a new Blog"%>
</div>
<% end %>

app/views/blogs/show.html.erb
<h1 class="blogPageTitle">Blog Page</h1>

<div class="blogShow">
  <% if @blog.user_id === current_user.id %>
  <div class="linkTitle"><%= @blog.title %><%= link_to "Edit Blog", edit_blog_path %></div>
  <% end %>
  <div class="linkContent"><%= @blog.content %></div>
</div>

<h3 class="addComment">Add a comment: </h3>

<div class="textArea">
<%= form_for @comment do |f| %>
<%= f.text_area :content%>
<%= hidden_field_tag "blog_id", @blog.id %>
<%= f.submit "Enter"%>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1 class="editComment">Edit Comment: </h1>

<div class="commentContent">
<%= form_for @comment do |f| %>
Content: <%= f.text_area :content %>
<%= f.submit "Enter"%>
</div>
<% end %>
<br>
<div class="deleteComment"><%= link_to "Delete Comment", comment_path, method: :delete %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MikeFolder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar">

    <%= link_to "Home", "/" %>

      <% if !logged_in? %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Log In", signin_path %>


      <% else %>

    <%= link_to "Log Out", logout_path, :method => "sessions#destroy" %>
    <%= link_to "View Blogs", blogs_path %>
    <%= link_to "Post Blog", new_blog_path %>
    
    <li class="currentUser"> <%= @user.username %></li>
      <% end %>

  </nav>

  <div class=design>
    <p id="about">Welcome to <strong>Comic-Media</strong> Blog, where we blog about comic book movies and t.v. shows from various cinematic universe.<br>
      Here users are given the platform to discuss in forms about characters, narratives, stroyline, blockbuster film deals, etc.
      This is where a group of comics, movie, and science fiction fans -- such as yourself -- can banded together and connect on a deeper level.<br>
      Comic-Media is inspired to become one of the focal point for the world of comic book entertainment, and other aspect aren't off topic, such as conventions, featuring comics and all aspects of the popular arts, any workshops and educational and academic programming such as the Comics Arts Conference; anime and film screenings (including a separate film festival); video games”; anything and everything surrounding the comics industry; we want to read your thoughts.
    </p>
  </div>


  <button id=""></button>
  <div class="usersNotice">
  <% if !flash[:notice].blank? %>
  <div>
    <%= flash[:notice] %>
  </div>
  <% end %>
  </div>
    <%= yield %>
    <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/edit.html.erb
<h1 class="updateUser">Update User</h1>

<div class="userUpdate">
<%= form_for @user do |f| %>
<div class="b">First Name: <%= f.text_field :first_name %></div>
<div class="b">Last Name: <%= f.text_field :last_name %></div>
<div class="b">Username: <%= f.text_field :username %></div>
<div class="b">Password: <%= f.text_field :password_digest %></div>
<div class="b">Email: <%= f.text_field :email %></div>
<div class="b"><%= f.submit "Edit User"%></div>
</div>
<% end %>
<div class="deletUser"><%= link_to "Delete User", user_path, method: :delete %></div>

app/views/users/index.html.erb
<h1 class="welcome">This is <strong class="comic">Comic-Media</strong> Blog</h1>
<p class="users">List of Users: </p>

<% @users.each do |u| %>
<div class="userList">
  <div id="userName"><strong><%= u.username %></strong></div>
  <div id="userEmail"><%= u.email %></div>
  <br>
  <hr>
</div>
<% end %>


<button id="btn" onclick="introduction()">Click Me</button>

app/views/users/new.html.erb
<h1 class="userSignUp">Sign Up</h1>


<div class="userSignIn">
<%= form_for @user do |f| %>
<div class="a">First Name: <%= f.text_field :first_name %></div>
<div class="a">Last Name: <%= f.text_field :last_name %></div>
<div class="a">Username: <%= f.text_field :username %></div>
<div class="a">Password: <%= f.text_field :password %></div>
<div class="a">Email: <%= f.text_field :email %></div>
<div class="a"><%= f.submit "New User"%></div>
<% end %>
</div>

app/views/users/show.html.erb
<h1 class="profileTitle"><%= @user.username %><div class="profileEditLink"><%= link_to "Edit Profile", edit_user_path %></div></h1>

<div class="profileUserShow">
  <div><%= @user.email %></div>
<br>

<%= link_to "Start A Blog", blogs_new_path %>


<div class="profilePage">
<% @user.blogs.each do |b| %>
<br>
<hr>
<div id="UserBlogTitle"><%= b.title %><a href="/blogs/<%=b.id %>/edit"><strong>"Edit Your Blog"</strong></a></div>
<br>
<div id="UserBlogContent"><%= b.content %></div>
<hr>

<div><a href="/blogs/<%=b.id %>/">"Blog Page"</a></div>

<% end %>
</div>